---
- name: Add system users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    state: present
    groups: "{{ item.groups | default(omit) }}"
  with_items:
    - "{{ ssh_users }}"
  tags: ['users']

- name: Add authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '../files/authorized_keys/{{ item.name }}') }}"
    exclusive: yes
  with_items:
    - "{{ ssh_users }}"
  tags: ['users']
